##
## Config file for default TES fit in mutau channel
## contact: saskia.falke@cern.ch
##

# NOTE: In general, the main information (channel, baselineCuts, etc.) should be given.
#       More specific sub-options (like weight replacement for systematic uncertainties) are optional
#       These are not needed for plotting only


channel: etau

baselineCuts: "q_1*q_2<0 && iso_1<0.10 && mvaFall17noIso_WP90_1 && idDeepTau2018v2p5VSjet_2>=5 && idDeepTau2018v2p5VSmu_2>=4 && !lepton_vetoes_notau && metfilter && idDeepTau2018v2p5VSe_2>=6"
regions:
    VVLVsele:
       definition: "idDeepTau2018v2p5VSe_2>=2"
       title: "VVLoose VSele"
    tightVsele:
       definition: "idDeepTau2018v2p5VSe_2>=6"
       title: "tight VSele"
    failVsele:
       definition: "idDeepTau2018v2p5VSe_2<2"
       title: "fail VSele"
    failVsele_endcap:
       definition: "idDeepTau2018v2p5VSe_2<2 && abs(eta_2) > 1.56 && abs(eta_2) < 2.5 && mt_1<60"
       title: "fail VSele endcap"
    failVsele_barrel:
       definition: "idDeepTau2018v2p5VSe_2<2 && abs(eta_2) < 1.46 && mt_1<60"
       title: "fail VSele barrel"
   
